services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command:
      [
        "redis-server",
        # "--requirepass", "yourpassword",
        "--appendonly", "yes",
        "--save", "900", "1",
        "--save", "300", "10",
        "--save", "60", "10000"
      ]
    volumes:
      - redis-data:/data

volumes:
  redis-data:
