services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS=--requirepass madre_pass --appendonly yes --save 900 1 --save 300 10 --save 60 10000
    volumes:
      - redis-data:/data

volumes:
  redis-data:
