services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command:
      [
        "redis-server",
        # "--requirepass", "yourpassword",
        "--appendonly", "yes",
        "--save", "900", "1",
        "--save", "300", "10",
        "--save", "60", "10000"
      ]
    volumes:
      - redis-data:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: always
    ports:
      - "8001:5540"
    depends_on:
      - redis
    environment:
      - REDISINSIGHT_HOST=0.0.0.0
      

volumes:
  redis-data:
